[tox]
minversion = 3.24.5
envlist = py3.7, flake8 #, mypy
isolated_build = True

# install_command = pip install {opts} {packages} --install-option="{posargs}"

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    pytest --basetemp={envtmpdir}


[testenv:flake8]
basepython = python3.7
deps = flake8
commands = flake8 python

# [testenv:mypy]
# basepython = python3.7
# deps =
#     -r{toxinidir}/requirements_dev.txt
# commands = mypy python

