import operator

from .functional import bf

lt          = bf(operator.lt)
le          = bf(operator.le)
eq          = bf(operator.eq)
ne          = bf(operator.ne)
ge          = bf(operator.ge)
gt          = bf(operator.gt)
not_        = bf(operator.not_)
truth       = bf(operator.truth)
is_         = bf(operator.is_)
is_not      = bf(operator.is_not)
abs         = bf(operator.abs)
add         = bf(operator.add)
and_        = bf(operator.and_)
floordiv    = bf(operator.floordiv)
index       = bf(operator.index)
inv         = bf(operator.inv)
lshift      = bf(operator.lshift)
mod         = bf(operator.mod)
mul         = bf(operator.mul)
matmul      = bf(operator.matmul)
neg         = bf(operator.neg)
or_         = bf(operator.or_)
pos         = bf(operator.pos)
pow         = bf(operator.pow)
rshift      = bf(operator.rshift)
sub         = bf(operator.sub)
truediv     = bf(operator.truediv)
xor         = bf(operator.xor)
concat      = bf(operator.concat)
contains    = bf(operator.contains)
countOf     = bf(operator.countOf)
delitem     = bf(operator.delitem)
getitem     = bf(operator.getitem)
indexOf     = bf(operator.indexOf)
setitem     = bf(operator.setitem)
length_hint = bf(operator.length_hint)
