name: Upload Conan Package

on:
  workflow_run:
    workflows: ["Build and Test with Conan", "Create Conan Package"]
    types: [completed]
  workflow_dispatch:
    inputs:
      upload:
        description: 'Upload package?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  upload_package:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11-ubuntu16.04  # Use the updated Docker image

    if: github.ref == 'refs/heads/main' || github.event.inputs.upload == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Conan Cache Path
        id: conan_cache
        run: echo "CONAN_CACHE_PATH=$(conan config home)" >> $GITHUB_ENV

      - name: Restore Conan Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CONAN_CACHE_PATH }}
          key: conan-${{ runner.os }}-${{ hashFiles('conanfile.*') }}
          restore-keys: conan-${{ runner.os }}-

      - name: Login to Conan
        run: conan remote login cosmic ${{ vars.COSMIC_CONAN_USER }} -p ${{ secrets.CONAN_TOKEN }}

      - name: Upload Package
        if: github.ref == 'refs/heads/main' || github.event.inputs.upload == 'true'
        run: conan upload "*" -r=cosmic --confirm --check