name: Create Conan Package

on:
  workflow_run:
    workflows: ["Setup dependencies using conan"]
    types: [completed]

jobs:
  create_package:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11-ubuntu16.04  # Use the updated Docker image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Conan Cache Path
        id: conan_cache
        run: echo "CONAN_CACHE_PATH=$(conan config home)" >> $GITHUB_ENV

      - name: Restore Conan Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CONAN_CACHE_PATH }}
          key: conan-${{ runner.os }}-${{ hashFiles('conanfile.*') }}
          restore-keys: conan-${{ runner.os }}-

      - name: Create Conan Package
        run: conan create . -s build_type=Release