name: Build and Test with Conan

on:
  workflow_run:
    workflows: ["Setup dependencies using conan"]
    types: [completed]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Conan Cache
        uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: conan-${{ runner.os }}-${{ hashFiles('conanfile.*') }}
          restore-keys: conan-${{ runner.os }}-

      - name: Install CMake and Conan
        run: pip install cmake conan

      - name: Install Dependencies
        run: conan install . -s build_type=Release

      - name: Configure CMake
        run: cmake . --preset=conan-release

      - name: Build
        run: cmake --build --preset=conan-release

      - name: Run Tests
        run: ctest --preset=conan-release